### ISSUE TITLE
Mcmmo support for Spigot 1.9

### ISSUE THREAD

**Issue by mibby** [mcMMO-Dev/mcMMO#2775]
Using McMMO dev 85 and Spigot 1.9

```
[00:20:50] [Server thread/ERROR]: Could not pass event PotionSplashEvent to mcMMO v1.5.04-SNAPSHOT-b85
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-b27d06a-32587ed]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-b27d06a-32587ed]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-b27d06a-32587ed]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-b27d06a-32587ed]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPotionSplashEvent(CraftEventFactory.java:325) [spigot.jar:git-Spigot-b27d06a-32587ed]
	at net.minecraft.server.v1_9_R1.EntityPotion.a(EntityPotion.java:137) [spigot.jar:git-Spigot-b27d06a-32587ed]
	at net.minecraft.server.v1_9_R1.EntityProjectile.m(EntityProjectile.java:164) [spigot.jar:git-Spigot-b27d06a-32587ed]
	at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1579) [spigot.jar:git-Spigot-b27d06a-32587ed]
	at net.minecraft.server.v1_9_R1.World.g(World.java:1554) [spigot.jar:git-Spigot-b27d06a-32587ed]
	at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1394) [spigot.jar:git-Spigot-b27d06a-32587ed]
	at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:627) [spigot.jar:git-Spigot-b27d06a-32587ed]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:787) [spigot.jar:git-Spigot-b27d06a-32587ed]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-b27d06a-32587ed]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:655) [spigot.jar:git-Spigot-b27d06a-32587ed]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-b27d06a-32587ed]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem cannot be cast to org.bukkit.inventory.meta.PotionMeta
	at com.gmail.nossr50.listeners.EntityListener.onPotionSplash(EntityListener.java:694) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor142.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-b27d06a-32587ed]
	... 15 more
```

**Comment by Puremin0rez** [comment]
I can confirm this issue.

**Comment by jordanwilliams1** [comment]
same here

**Comment by Tslat** [comment]
Yeah the plugin needs a heavy rewrite for 1.9
The entirety of Alchemy is broken, due to the major change in the way bukkit handles potions
Sound enums changed, so they'll cause errors

And various other little things

It's taking me a while to update my private version of mcmmo, I daresay it'll take them a while to do the same for the main branch

**Comment by MrKiller01** [comment]
Well, i do not have to say anything, those gents before me did the job already... A pity everything depending on it will now not function right so i have to unload the plugin until.....

**Comment by Sikatsu** [comment]
Seems toothpick is working on 1.9 support already, hope he can get something done for us soon. Appreciate the dev's work.

**Comment by t00thpick1** [comment]
I have sounds and biomes updated to the new enums (@Tslat  you should do what I did for your private branch)  I error logs and descriptions of what you were doing for anything else,  to my current understanding bukkit itself has not accounted for new potions in 1.9 yet, so that remains a spigot/bukkit issue until I am told otherwise.  The scoreboard error is somethign to look at.

**Comment by Tslat** [comment]
@t00thpick1 
As far as I can see, the entire potions system has been redone (properly) in Bukkit.
I haven't begun to re-write it yet so I may be wrong though.

Looks to me like they've moved to separate Item IDs and metadata rather than Byte indexing for potions.

I completely split from the main McMMO project a while back though, given that my code is somewhat different to yours now;
My private branch has the entire plugin re-balanced, as well as the basic addition of a cooking skill, archery active ability, and an almost finished Blocking skill (for shields). Perks/Bypasses/Luckys are soon be removed too (I always have them disabled anyway, and they tend to cause issues with permissions.

In case you need some things:
- Food consumption needs handling for offhand items
- Alchemy needs to be re-done
- Ability activations may need some thought (Main hand vs offhand, edge cases)

I can't seem to replicate the log that cosmosis has posted above...

I'm more than happy to offer any knowledge I may have of the changes if needed, but my code is sufficiently different that I feel git pushes may not be viable

**Comment by t00thpick1** [comment]
@Tslat From what I just saw, the only change in the Potion API was the addition of a Color field, that does not break compatability.

**Comment by Tslat** [comment]
@t00thpick1 
Odd.. I haven't changed the alchemy code at all, and yet every potion that is brewed outputs as an invalid item.
I'm almost completely sure they've moved away from Byte indexing on potions..
Does your main branch test fine ingame for brewing?

**Comment by t00thpick1** [comment]
@Tslat You are discussing implementation.  THe potions API has not changed.  Their implementation is broken.  Thats a spigot bug.

**Comment by t00thpick1** [comment]
Oh hmm I was under the assumption we used the Potion API..

**Comment by Tslat** [comment]
@t00thpick1 
Yeah haha, you had me completely stumped for a moment then
Their changes seem completely intentional, and in my opinion are for the better

Means that McMMO no longer works for Alchemy at all though

**Comment by Tslat** [comment]
To add to that, there also appears to be an inventory ArrayIndexOutOfBoundsException problem for InventoryClickEvent
But it's not throwing the full stacktrace, so I haven't managed to figure out what's causing it

**Comment by t00thpick1** [comment]
@Tslat wanna do me a favor and update the Potions config for the new alchemy method Im about to push?  I did the first two as an example.

**Comment by Tslat** [comment]
@t00thpick1
I would, but I'm at work for the next 7 hours or so, sorry
Don't have any access to my files at the moment

**Comment by t00thpick1** [comment]
@Tslat Theoretically I can wait that long as I'd really rather not do that part..

**Comment by TowerGuardian** [comment]
`01.03 17:03:25 [Server] WARN Exception in thread "Craft Scheduler Thread - 1" 01.03 17:03:25 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin mcMMO v1.5.04-SNAPSHOT-b82 generated an exception while executing task 9 01.03 17:03:25 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56) 01.03 17:03:25 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 01.03 17:03:25 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 01.03 17:03:25 [Server] INFO at java.lang.Thread.run(Thread.java:745) 01.03 17:03:25 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player; 01.03 17:03:25 [Server] INFO at com.gmail.nossr50.metrics.mcstats.Metrics.postPlugin(Metrics.java:502) 01.03 17:03:25 [Server] INFO at com.gmail.nossr50.metrics.mcstats.Metrics.access$500(Metrics.java:45) 01.03 17:03:25 [Server] INFO at com.gmail.nossr50.metrics.mcstats.Metrics$1.run(Metrics.java:353) 01.03 17:03:25 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) 01.03 17:03:25 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) 01.03 17:03:25 [Server] INFO ... 3 more 01.03 17:03:25 [Server] WARN Exception in thread "Craft Scheduler Thread - 3" 01.03 17:03:25 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin EMetrics v0.0.4 generated an exception while executing task 8 01.03 17:03:25 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56) 01.03 17:03:25 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 01.03 17:03:25 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 01.03 17:03:25 [Server] INFO at java.lang.Thread.run(Thread.java:745) 01.03 17:03:25 [Server] INFO Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player; 01.03 17:03:25 [Server] INFO at com.gmail.nossr50.metrics.mcstats.Metrics.postPlugin(Metrics.java:502) 01.03 17:03:25 [Server] INFO at com.gmail.nossr50.metrics.mcstats.Metrics.access$500(Metrics.java:45) 01.03 17:03:25 [Server] INFO at com.gmail.nossr50.metrics.mcstats.Metrics$1.run(Metrics.java:353) 01.03 17:03:25 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) 01.03 17:03:25 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53) 01.03 17:03:25 [Server] INFO ... 3 more 01.03 17:03:25 [Server] INFO UUID upgrade completed!
`
Spigot 1.9 Build #49

Clean Server

**Comment by Tslat** [comment]
@TowerGuardian
Update your spigot build
I believe that's a spigot issue, which was resolved about 12 hours ago

**Comment by t00thpick1** [comment]
@TowerGuardian update your mcMMO build, that must be ancient.  I removed metrics and the old getOnlinePlayers ages ago.

**Comment by t00thpick1** [comment]
Update on compatability update: Alchemy should work on 1.9 now,  it may need config updates

**Comment by Sikatsu** [comment]
The config won't auto update for 1.9 later on? Nice work :)

**Comment by t00thpick1** [comment]
Actually looks like I lied,  Spigot has no way of accessign/setting potion types as of yet for 1.9.  Thats disappointing.  Its halfway there though, once they write up an API I can adapt to it.

**Comment by Sikatsu** [comment]
Keep up the good work! Everything else should work on 1.9?

**Comment by Cosmosis42** [comment]
Looks like the scoreboards issue is an issue with all sidebar scoreboards, not just MCMMO.

**Comment by Tslat** [comment]
@t00thpick1
So your patch didn't fix alchemy?
I was sure i had a working method for alchemy.. I looked at it with the spigot prebuilds before release

I'm fixing other stuff in my branch at the moment, but I'll give alchemy a look when i get to it

**Comment by t00thpick1** [comment]
@Tslat There is currently no way to fix alchemy,  I don't htink potions have a useable api in bukkit right now.

**Comment by Tslat** [comment]
@t00thpick1 
You think you're gonna try add support for offhand usage?
I'm considering it, but it looks like a fair bit of work

**Comment by NullYing** [comment]
So how long can solve the problem？

**Comment by Tslat** [comment]
@NullYing

Which problem?
You should be able to use it for 1.9 now, but Alchemy still doesn't work -- and it's not proven to be stable yet.

**Comment by t00thpick1** [comment]
@Tslat
My plan is to just move to shift-clicks for abilities.

Also I am in the process of giving Spigot a patch to fix Potions API's  if they take it, then I can fix alchemy, if not, then alchemy's a goner

**Comment by Tslat** [comment]
@t00thpick1 
I'm just in the process of removing lucky/bypass/perks from my branch, but once I'm done that I'll look into Alchemy..
I'm almost certain that I had a working temp method before release on the prebuilds
You're probably right, but I'll look into it anyway and get back to you

I was referring to the passive abilities though; I.E. Farmer's Diet, Fisherman's Diet, Green Thumb, etc..

**Comment by t00thpick1** [comment]
@Tslat  Don't waste your time, unless you do direct NBT editing/reading there is no way to do it right now.  However I have this https://gist.github.com/t00thpick1/d893aea46aa9e2a4e0c5  patch for spigot that they may or may not take, and it *should* work assuming it actually compiles, I wrote it in notepad++ so might-of missed something.

**Comment by Tslat** [comment]
Looks fine, here's hoping
If they don't accept it, then we're still stuck with the current alchemy problem though ; )

**Comment by t00thpick1** [comment]
@Tslat Worst case I have to write an NMS reflection layer.

**Comment by dbsps** [comment]
@t00thpick1 might want to consider ctrl instead of shift for the ability activation. Otherwise you might end up enabling the ability while someone is using sneak to avoid falling off a platform while working.

**Comment by Tslat** [comment]
@dbsps 
We don't check for specific keys, we just check if the player is crouching or not. The key that is used doesn't affect anything.

We don't have any ability to track keypresses, since they are handled client-side without any packet transfer to the Server

I've added an optional empty offhand check to my branch, maybe I could suggest you add the same to yours, t00thpick?

**Comment by dbsps** [comment]
@tslat ah that makes a lot of sense. I've never made any minecraft plugins so I didn't know what info is passed but given a player can change the keybinding passing the effect rather than the cause does make a lot of sense. Cheers for taking the time to explain :-)

**Comment by mibby** [comment]
Looking forward to the potion API to fix this error. :)

```
[22:36:33] [Server thread/ERROR]: Could not pass event PotionSplashEvent to mcMMO v1.5.04-SNAPSHOT-b92
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-3af4605-ed8cef0]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-3af4605-ed8cef0]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-3af4605-ed8cef0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-3af4605-ed8cef0]
	at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callPotionSplashEvent(CraftEventFactory.java:339) [spigot.jar:git-Spigot-3af4605-ed8cef0]
	at net.minecraft.server.v1_9_R1.EntityPotion.a(EntityPotion.java:137) [spigot.jar:git-Spigot-3af4605-ed8cef0]
	at net.minecraft.server.v1_9_R1.EntityProjectile.m(EntityProjectile.java:164) [spigot.jar:git-Spigot-3af4605-ed8cef0]
	at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1579) [spigot.jar:git-Spigot-3af4605-ed8cef0]
	at net.minecraft.server.v1_9_R1.World.g(World.java:1554) [spigot.jar:git-Spigot-3af4605-ed8cef0]
	at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1394) [spigot.jar:git-Spigot-3af4605-ed8cef0]
	at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:627) [spigot.jar:git-Spigot-3af4605-ed8cef0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:792) [spigot.jar:git-Spigot-3af4605-ed8cef0]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-3af4605-ed8cef0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-3af4605-ed8cef0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-3af4605-ed8cef0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_9_R1.inventory.CraftMetaItem cannot be cast to org.bukkit.inventory.meta.PotionMeta
	at com.gmail.nossr50.listeners.EntityListener.onPotionSplash(EntityListener.java:694) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-3af4605-ed8cef0]
	... 15 more
```

**Comment by TheOtakuJames** [comment]
I hope there will be an update for 1.9 soon, as currently MCMMO does not work at all... There are no errors in console, but no skills are working, and /mcmmo brings nothing up.

**Comment by Tslat** [comment]
@TheOtakuJames 
Then Mcmmo didn't start up when the server started.
Check the logs back when you started up the server, there'll be an error there

**Comment by Tslat** [comment]
@mibby 
I believe that method may be redundant anyway, for now.
I only managed a brief look, but it seems that minecraft (and spigot by extension) no longer support custom potion types.

**Comment by Wsine** [comment]
same problem. hope mcmmo can support mc1.9 soon.

**Comment by TheOtakuJames** [comment]
@Tslat Here's the whole error I just found while looking through logs:
http://pastebin.com/un6rvUzx

**Comment by Tslat** [comment]
@TheOtakuJames 
That was already fixed, update your mcmmo version and update your spigot version

**Comment by t00thpick1** [comment]
@TheOtakuJames I notice you are approx...  200 versions behind on mcMMO?

**Comment by TheOtakuJames** [comment]
@Tslat @t00thpick1 I hadn't been having this problem until I updated my Spigot from 1.8.9 to 1.9, and I am using the latest mcMMO version according to my BukGet Plugin list on the server host, I check it regularly to see when it's ready for an update.

**Comment by Tslat** [comment]
You're using the last version freely available

The version you're using is so old, it wasn't even built for 1.8.
Newest versions are available here:
https://www.spigotmc.org/resources/mcmmo.2445/

The fact that it only broke with 1.9 shows that the methods used in your version are far outdated and unstable now.

**Comment by TheOtakuJames** [comment]
@Tslat  All fixed now, bought mcMMO. Thanks for the help

**Comment by Sikatsu** [comment]
@Tslat @t00thpick1 Any news about a fix for when blocking with your shield? It keeps spamming ''Your skill is not ready yet''

**Comment by Tslat** [comment]
@Sikatsu 
Just change the Only_Activate_When_Sneaking line in your config from false to true
More than shields are affected, we're just going to go to activations while crouching

**Comment by Sikatsu** [comment]
@Tslat Ah, so that will be default from now on actually? Thanks

**Comment by t00thpick1** [comment]
@Sikatsu  Until I get to that portion of the update and decide what to do with it, yes

**Comment by Sikatsu** [comment]
So then what exactly you need to do to enable your ability? Instead of right click just click shift?

**Comment by Sikatsu** [comment]
And wouldn't the ability always turn on when you crouch while building for example?

**Comment by t00thpick1** [comment]
shift and right click.

**Comment by Tslat** [comment]
Only in the rather specific circumstance in which you're:
1. Crouched while building
2. Holding an ability tool in your main hand
3. Building with your offhand
4. Decide to left click after right clicking for some reason

It can still happen, but other suggestions are welcome if you have them

**Comment by DorCoMaNdO** [comment]
I've made a different solution to the issue with the ability activations, #2782, you're only required to sneak if you have an item in your offhand and you're not in a vehicle, otherwise it's just right click.

Those who don't use the offhand won't be affected by the change, it's supposed to reduce the spam and accidental activations for those who do, the "Only_Activate_When_Sneaking" setting doesn't consider the offhand (nor any vehicle for that matter, so you'd have to dismount to activate an ability), you could still use that setting though, even with my changes.

**Comment by Tslat** [comment]
@DorCoMaNdO 

Good idea, but I'm not sure that consistency is worth forgoing for something like that

Might be a personal preference thing for me, not sure

**Comment by DorCoMaNdO** [comment]
I am not a fan of the offhand, stuff like the shield appear to be too big to my liking, which is why I don't use it, anyone else who doesn't use it, as I mentioned above, is basically unaffected, otherwise it's just simple logic to remember to yourself, you need to sneak when you're not in a vehicle, otherwise you don't since you'd dismount.

You could turn this to a setting as well, just in case someone would like to disable that I guess.

Slightly offtopic: Any idea why my builds never show a build number? It's "b${BUILD_NUMBER}" instead, I am assuming my IDE (NetBeans 8.1) doesn't replace it, but I've got no idea how to fix that.

**Comment by Sikatsu** [comment]
@Tslat So in the future of McMMO either with sneak or without sneak you will always have some problems with it? And which one causes the less problems? It would be irritating if you are crouching and building your roof and mcmmo keeps spamming messages.

**Comment by DorCoMaNdO** [comment]
@Sikatsu mcMMO will not show any message like "you ready your hand" if your main hand is holding a building block, unless you're building with the offhand and you have nothing or a tool in the main hand, you're good.

**Comment by Tslat** [comment]
Well I only work on my branch, and I assume dor does something of his own too.

The final product will be dependent on what t00thpick1 wants to do, since he runs the main branch.
Dor's solution is probably the one that reduces the most edge cases, but I really don't like reducing consistency, so I may not implement it in my branch, maybe just as a non-default optional

**Comment by EvilOlaf** [comment]
@dorcomando the build number is set by the CI. So when you build local maven does not replace this variable. Either ignore it or set it by hand editing your pom.xml

**Comment by Sikatsu** [comment]
Isn't there any other key possible like middle mouse button?

**Comment by Sikatsu** [comment]
I'm having issues with McMMO on 1.9 with MySQL. Everytime I restart the server, the config seems to be reset? Using #95

**Comment by Sikatsu** [comment]
@t00thpick1 The McMMO abilities are causing lagg when you use them. Any fix for this besides disabling? xD

**Comment by Sikatsu** [comment]
@Tslat 
There where no issues on 1.8 with this host and mcmmo abillities. My CPU is E3-1230 and I even have more ram then before.

**Comment by Tslat** [comment]
@Sikatsu 
Minecraft took a rather serious hit to performance with 1.9, in some places even so much so that professional servers are crashing from thread overworking.

I don't know if t00thpick1 has changed any of the ability code, but it looks fine to me, so I'm gonna say it's spigot/minecraft causing the lag problems.

**Comment by t00thpick1** [comment]
Potions are functional now :D  !!!!!!

**Comment by t00thpick1** [comment]
Closing this as most if not all 1.9 updates are done,  open new issues for anything new found

**Comment by 151baccardi** [comment]
but where and how do I get the actual working mcmmo.jar file ? Thanks

**Comment by Tim-Schneider** [comment]
@151baccardi https://ci.drtshock.net/job/MCMMO/

**Comment by 151baccardi** [comment]
Thanks. After a lot of searching I found this. But thanks for the link anyways.
I love MCMMO. Hope it never breaks.

**Comment by toodabeans** [comment]
So I added the newest version of Mcmmo to my 1.9 server and whenever I use any of the commands, nothing happens. Nothing shows up in chat either. I'm able to do /help mcmmo and see all of the commands, but nothing works. What should I do?

**Comment by Tslat** [comment]
Do you have your permissions set up properly?

**Comment by toodabeans** [comment]
What would I have to edit? (I'm not used to minecraft servers so I'm kinda shit at this, I'm used to Gmod and Valve games.)

**Comment by toodabeans** [comment]
All of my other addons work fine, I just need help with Mcmmo

**Comment by Tslat** [comment]
Are you hosting a server, or just running one for yourself?
IF you're hosting one, you should really try learn about permissions systems and such first.

If it's for yourself, just op yourself through the server console with /op <player>

**Comment by DorCoMaNdO** [comment]
If you upgraded from an older version, remove all the configs and let them regenerate at startup, most configs do not automatically update so parts removed and/or added by server owners would not get rewritten or removed, but some things have changed, making older configs incompatible.

**Comment by toodabeans** [comment]
This is a clean server. Just bought yesterday, only installed Spigot 1.9 onto it and then my plugins. And yes, I do have it hosted through a website. Every other plugin I have downloaded works fine, and hasn't really caused me any issues.

**Comment by Tslat** [comment]
Op yourself and see if you still have the issue.
IF you don't, then it's a permissions problem

**Comment by toodabeans** [comment]
I'm opped. This isn't my first time hosting a server, so I know all of the basics

**Comment by toodabeans** [comment]
I have the IP right here, if anyone would like to come see if they could figure out a solution ( 209.222.96.42:25575 )

**Comment by Tslat** [comment]
Was there any errors on server startup?

**Comment by toodabeans** [comment]
In the console? Not that I noticed, Let me restart and check.

**Comment by Tslat** [comment]
Issue resolved. His Spigot was out of date

**Comment by toodabeans** [comment]
My host claimed that my version Spigot was on the latest version. Where would I go to show him otherwise?

**Comment by Tslat** [comment]
Run /version

When I checked, you were roughly 45 versions behind.

**Comment by toodabeans** [comment]
Yep! You were right. Got it working. Thanks!

**Comment by GothCartel** [comment]
Still cannot seem to get alchemy working, I am running the latest mcmmo jar and bukkit 1.9.2 but the console states that the alchemy potions aren't being loaded.. any idea?

**Comment by Tslat** [comment]
Did you let your potions config regenerate?

**Comment by GothCartel** [comment]
Ive taken out mcmmo jar, added new version, taken out an reinstalled both new versions of the mcmmo jar and bukkit 1.9.2 and still nothing.. the smelting works fine just cant seem to get the potions to work.. let me quickly look at the potions file

**Comment by GothCartel** [comment]
hmmm no its still saying the march 16th rebuild, the backup and flatfile have todays date, in fact they are the only ones that changed

**Comment by GothCartel** [comment]
would I need to delete the potions file, then restart the server with the new mcmmo jar?

**Comment by GothCartel** [comment]
That's the outout from latest logfile regarding the alchemy issue
[Server thread/INFO]: [mcMMO] Enabling mcMMO v1.5.04-SNAPSHOT-b118
[13:41:30] [Server thread/WARN]: [mcMMO] Invalid material: POTION_POISON
[13:41:30] [Server thread/WARN]: [mcMMO] Potion format for Treasures.yml has changed
[13:41:30] [Server thread/WARN]: [mcMMO] Invalid material: POTION_INSTANT_HEAL
[13:41:30] [Server thread/WARN]: [mcMMO] Potion format for Treasures.yml has changed
[13:41:30] [Server thread/WARN]: [mcMMO] Invalid material: POTION_FIRE_RESISTANCE
[13:41:30] [Server thread/WARN]: [mcMMO] Potion format for Treasures.yml has changed
[13:41:30] [Server thread/WARN]: [mcMMO] Invalid material: POTION_SPEED
[13:41:30] [Server thread/WARN]: [mcMMO] Potion format for Treasures.yml has changed
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 64
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 832
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 1088
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 2112
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 2368
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 2880
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 3904
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 4416
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 5184
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 5440
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 5696
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 17216
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 17472
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 18496
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 18752
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 19264
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 20288
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 20800
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 21568
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 21824
[13:41:30] [Server thread/WARN]: [mcMMO] Failed to load Alchemy potion: 22080
[13:41:31]

**Comment by t00thpick1** [comment]
Update spigot, update mcMMO

**Comment by GothCartel** [comment]
I'm using the latest mcmmo and bukkit 1.9.2 would spigot be better then?

**Comment by GothCartel** [comment]
you Sir are a genius of the highest order it looks like it was bukkit causing the issue, changed to spigot, removed the potions yml and restarted the server, had to reinstate a scoreboard but that was a minor issue.. all working fine.. Many Many thanks :)

**Comment by gaiaweylyn** [comment]
Do the latest builds available here work with 1.8.9? https://ci.drtshock.net/job/MCMMO/

**Comment by Tslat** [comment]
No, they support 1.9 only

**Comment by EvilOlaf** [comment]
True. Support for 1.8 has been dropped. If I understood correctly the support for 1.8 MAY come back somewhen.

**Comment by gaiaweylyn** [comment]
I hope so. Most of my friends don't particularly like the 1.9 update, so my server is staying on 1.8.

**Comment by Tslat** [comment]
I wouldn't count on it
